### ISSUE TITLE
React front

### ISSUE THREAD

**Issue by mgcth** [Ingenjorsarbete-For-Klimatet/ifk-sverige#9]
**Description**

Add a simple frontend with some menus in React. I'll look into a good library and add to this issue.

- [x] deck.gl
- [x] vite
- [x] shadcn
- [x] configs
- [x] zustand
- [x] react-select
- [x] react and some unstyled components and loose functionality

Loosely implemented using typescript (without much type support for now).

**Comment by docNord** [comment]
@christian-ek have you seen this repo yet? We (well, @mgcth) are building an interactive map tool as a basis where we are planning to showcase things such as smhi-data, flood risk calculation results and other tools necessary for climate change adaptation and green energy infrastructure planning. Figured it could be something you'd find interesting :)
